Vagrant.configure(2) do |config|
  config.vm.define "fedora" do |fedora|

    config.vm.box = "../package.box"

    config.vm.provider "virtualbox" do |vbox|
      vbox.memory = 512
      vbox.cpus = 2
    end
  end
end
