Vagrant.configure(2) do |config|
  config.vm.define "fedora" do |fedora|

    config.vm.box = "../Fedora-Cloud-Base-Vagrant-22-20150521.x86_64.vagrant-virtualbox.box"

    config.vm.provider "virtualbox" do |vbox|

      cpus = `sysctl -n hw.ncpu`.to_i
      # sysctl returns Bytes and we need to convert to MB
      mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4

      vbox.memory = mem
      vbox.cpus = cpus
    end

    # y u no do this for vagrant halt then??
    config.ssh.insert_key = false
  end

  config.vm.provision :shell, path: "bootstrap.sh"
end
